site_name: Gloom Haven Helper
nav:
  - Home: index.md
  - API Requests:
      - Monsters: api/monsters.md
      - Monster Instances: api/monsterinstances.md
      - Rooms: api/rooms.md
  - FAQ: about.md
theme: readthedocs
